### ISSUE TITLE
example run?

### ISSUE THREAD

**Issue by brettva** [ZhiGroup/RAFFI#1]
Hi,

I seem to be having a lot of trouble getting this to run, example command with example input and output files might help with troubleshooting. Would this be possible? Thank you.

**Comment by ardalan-n** [comment]
Hi,
Thank you for your interest in our program. I'll try to add some examples soon. Meanwhile, I hope the following description can be helpful:
The current version assumes the VCF files are provided in 22 separate files (one file for each chromosome) and they all have a similar prefix. For example, assume you can have all the VCF files for each chromosome in a folder called `../myfiles/`, and the file names are as follows:
```
panel1_chr1.vcf.gz
panel1_chr2.vcf.gz
...
panel1_Chr22.vcf.gz
```
Then the arguments would be:
`-i ../myfiles/ -v panel1_chr  -g ../my_mapping_files/`

`-g `should point to a folder containing all genetic mapping files for the VCF inputs (`../my_mapping_files/`).  For each chromosome, you need to provide a genetic mapping file that has the genetic location for each site in the VCF file.

```
chr1.rMap
...
chr22.rMap
```
The program can also use IBD segments directly from [RaPID](https://github.com/ZhiGroup/RaPID) outputs. In this case, you use the tag `-O <RaPID_output_dir>`. 

Best,
Ardalan

**Comment by catheriz** [comment]
I tried to run but always got IndexError: list index out of range, but my inputs are -i <input folder>  -v <vcf prefix>  -g {genetic mapping file path} -p {Python version} -o {output directory}

**Comment by ardalan-n** [comment]
I uploaded a small haplotype panel including the genetic map for the sites in the panel (please see example folder). You can navigate to the Debug folder and type:
./RAFFI_v.0.1 -i ../example/vcf_files/ -v maf_0.2_chr -g ../example/genetic_maps/ -o ../example/

Best,
Ardalan
