### ISSUE TITLE
Human Chromosome Number Hard Coded Into Binary

### ISSUE THREAD

**Issue by brittneykeel** [ZhiGroup/RAFFI#2]
Hello,

I am attempting to run the binary version provided in the Debug folder. I am working with pig, which has 18 chromosomes. When I try to run, I get an error that it cannot find a VCF for chr22. I am assuming that the human chromosome number may be hard coded in.

**Comment by ardalan-n** [comment]
Hi,

The code was written and tested mainly for the human genome and the number 22 was hard coded. I just uploaded a new binary version (v.0.2) that allows you to change the number of chromosomes (using -c ).

Best,
Ardalan

**Comment by ardalan-n** [comment]
[RAFFI_v.0.2](https://github.com/ZhiGroup/RAFFI/blob/master/Debug/RAFFI_v.0.2)
